targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/features/chat/data/models/chat/assistant_content.dart
      json_serializable:
        generate_for:
          include:
            - lib/features/chat/data/models/chat/assistant_content.dart
            - lib/core/session/session_state.dart
    options:
      exclude:
        - test/**
