import 'package:chatorai/features/chat/data/models/chat_models.dart'
    as chat_models;
import 'package:chatorai/shared/utils/message_action.dart';
import 'package:flutter/material.dart';

bool canDeleteMessage(chat_models.Message message) {
  if (message.role == chat_models.MessageRole.system) {
    return false;
  }
  return true;
}

bool canEditMessage(chat_models.Message message) {
  return message.role == chat_models.MessageRole.user;
}

bool canRegenerateMessage(chat_models.Message message) {
  // Compaction summaries are generated by the hidden `compaction` agent and
  // cannot be regenerated as a normal assistant turn.
  if (message.isCompactionSummary) return false;
  return message.role == chat_models.MessageRole.assistant;
}

List<MessageAction> getMessageActions(chat_models.Message message) {
  final List<MessageAction> actions = [];

  if (canDeleteMessage(message)) {
    actions.add(
      MessageAction(
        icon: Icons.delete,
        label: 'Delete',
        localizedLabel: {'en': 'Delete', 'ru': 'Удалить'},
        action: MessageActionType.delete,
        color: Colors.red,
      ),
    );
  }

  if (canEditMessage(message)) {
    actions.add(
      MessageAction(
        icon: Icons.edit,
        label: 'Edit',
        localizedLabel: {'en': 'Edit', 'ru': 'Редактировать'},
        action: MessageActionType.edit,
        color: Colors.blue,
      ),
    );
  }

  if (canRegenerateMessage(message)) {
    actions.add(
      MessageAction(
        icon: Icons.refresh,
        label: 'Regenerate',
        localizedLabel: {'en': 'Regenerate', 'ru': 'Перегенерировать'},
        action: MessageActionType.regenerate,
        color: Colors.blue,
      ),
    );
  }

  if (message.role != chat_models.MessageRole.system) {
    actions.add(
      MessageAction(
        icon: Icons.copy_all,
        label: 'Copy',
        localizedLabel: {'en': 'Copy', 'ru': 'Копировать'},
        action: MessageActionType.copy,
        color: Colors.grey,
      ),
    );
  }

  if (message.role != chat_models.MessageRole.system) {
    actions.add(
      MessageAction(
        icon: Icons.share,
        label: 'Share',
        localizedLabel: {'en': 'Share', 'ru': 'Поделиться'},
        action: MessageActionType.share,
        color: Colors.green,
      ),
    );
  }

  return actions;
}
